"""
This type stub file was generated by pyright.
"""

run = ...
def on_pretrain_routine_start(trainer) -> None:
    """Initialize NeptuneAI run and log hyperparameters before training starts."""
    ...

def on_train_epoch_end(trainer) -> None:
    """Log training metrics and learning rate at the end of each training epoch."""
    ...

def on_fit_epoch_end(trainer) -> None:
    """Log model info and validation metrics at the end of each fit epoch."""
    ...

def on_val_end(validator) -> None:
    """Log validation images at the end of validation."""
    ...

def on_train_end(trainer) -> None:
    """Log final results, plots, and model weights at the end of training."""
    ...

callbacks = ...
