"""
This type stub file was generated by pyright.
"""

from .inference import InferenceModel

class CLIPModel(InferenceModel):
    """
    Run inference on CLIP, hosted on Roboflow.
    """
    def __init__(self, api_key: str) -> None:
        """
        Initialize a CLIP model.

        Args:
            api_key: Your Roboflow API key.
        """
        ...
    


