"""
This type stub file was generated by pyright.
"""

from .inference import InferenceModel

class GazeModel(InferenceModel):
    """
    Run inference on a gaze detection model, hosted on Roboflow.
    """
    def __init__(self, api_key: str, version_id: str) -> None:
        """
        Initialize a CLIP model.

        Args:
            api_key: Your Roboflow API key.
            version_id (str): the ID of the dataset version to use for inference
        """
        ...
    


