"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from ultralytics.engine.model import Model

class NAS(Model):
    """
    YOLO-NAS model for object detection.

    This class provides an interface for the YOLO-NAS models and extends the `Model` class from Ultralytics engine.
    It is designed to facilitate the task of object detection using pre-trained or custom-trained YOLO-NAS models.

    Attributes:
        model (torch.nn.Module): The loaded YOLO-NAS model.
        task (str): The task type for the model, defaults to 'detect'.
        predictor (NASPredictor): The predictor instance for making predictions.
        validator (NASValidator): The validator instance for model validation.

    Methods:
        info: Log model information and return model details.

    Examples:
        >>> from ultralytics import NAS
        >>> model = NAS("yolo_nas_s")
        >>> results = model.predict("ultralytics/assets/bus.jpg")

    Notes:
        YOLO-NAS models only support pre-trained models. Do not provide YAML configuration files.
    """
    def __init__(self, model: str = ...) -> None:
        """Initialize the NAS model with the provided or default model."""
        ...
    
    def info(self, detailed: bool = ..., verbose: bool = ...) -> Dict[str, Any]:
        """
        Log model information.

        Args:
            detailed (bool): Show detailed information about model.
            verbose (bool): Controls verbosity.

        Returns:
            (Dict[str, Any]): Model information dictionary.
        """
        ...
    
    @property
    def task_map(self) -> Dict[str, Dict[str, Any]]:
        """Return a dictionary mapping tasks to respective predictor and validator classes."""
        ...
    


