"""
This type stub file was generated by pyright.
"""

class DeploymentApiError(Exception):
    ...


def add_deployment(api_key, creator_email, machine_type, duration, delete_on_expiration, deployment_name, inference_version): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def get_deployment(api_key, deployment_name): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def list_deployment(api_key): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def get_workspace_usage(api_key, from_timestamp, to_timestamp): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def get_deployment_usage(api_key, deployment_name, from_timestamp, to_timestamp): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def pause_deployment(api_key, deployment_name): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def resume_deployment(api_key, deployment_name): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def delete_deployment(api_key, deployment_name): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def list_machine_types(api_key): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

def get_deployment_log(api_key, deployment_name, from_timestamp=..., to_timestamp=..., max_entries=...): # -> tuple[int, str] | tuple[Literal[200], Any]:
    ...

