"""
This type stub file was generated by pyright.
"""

def count_class_occurances(predictions, target_class): # -> int:
    ...

def count_comparisons(predictions, required_objects_count, required_class_count, target_class): # -> bool:
    ...

def check_box_size(prediction, minimum_size_requirement, maximum_size_requirement): # -> bool:
    ...

def base64_encode(image_path): # -> str:
    ...

def clip_encode(image1, image2, CLIP_FEATURIZE_URL): # -> float:
    ...

