"""
This type stub file was generated by pyright.
"""

def write_line(line): # -> None:
    ...

class Retry:
    def __init__(self, max_retries, retry_on) -> None:
        ...
    
    def backoff(self): # -> None:
        """
        Backoff for a random time based on number of retries.
        """
        ...
    
    def __call__(self, func, *args, **kwargs): # -> None:
        ...
    


