"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple

def get_wrong_dependencies_versions(dependencies_versions: List[Tuple[str, str, str]]) -> List[Tuple[str, str, str, str]]:
    """
    Get a list of mismatching dependencies with current version installed.
    E.g., assuming we pass `get_wrong_dependencies_versions([("torch", "==", "1.2.0")]),
        we will check if the current version of `torch` is `==1.2.0`. If not,
        we will return `[("torch", "==", "1.2.0", "<current_installed_version>")]

    We support `<=`, `==`, `>=`

    Args:
        dependencies_versions (List[Tuple[str, str]]): List of dependencies
            we want to check, [("<package_name>", "<version_number_to_check")]

    Returns:
        List[Tuple[str, str, str]]: List of dependencies with wrong version,
            [("<package_name>", "<version_number_to_check", "<current_version>")]
    """
    ...

def print_warn_for_wrong_dependencies_versions(dependencies_versions: List[Tuple[str, str, str]], ask_to_continue: bool = ...): # -> None:
    ...

def warn_for_wrong_dependencies_versions(dependencies_versions: List[Tuple[str, str, str]]): # -> Callable[..., Callable[..., None]]:
    """
    Decorator to print a warning based on dependencies versions. E.g.

    ```python
    @warn_for_wrong_dependencies_versions([("torch", "==", "1.2.0")])
    def foo(x):
        # I only work with torch `1.2.0` but another one is installed
        print(f"foo {x}")
    ```

    prints:

    ```
    Dependency torch==1.2.0 is required but found version=1.13.1,
        to fix: `pip install torch==1.2.0`
    ```

    Args:
        dependencies_versions (List[Tuple[str, str]]): List of dependencies
            we want to check, [("<package_name>", "<version_number_to_check")]
    """
    ...

def normalize_yolo_model_type(model_type: str) -> str:
    ...

